data_cfg:
  dataset_name: MMGait_Single_Pose2d
  dataset_root: /path/to/MMGait
  dataset_partition: ./datasets/MMGait/mmgait.json
  num_workers: 8
  data_in_use: [false, false, false, false, false, false, false, true, false, false, false, false, false] 
  # depth, event, heatmap, ir, ir_sils, lidar_depth, lidar_points, pose2d, pose3d, radar4d, radar_depth, rgb, rgb_sils  
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: MMGait_Single_Pose2d

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 3000
  save_name: GaitGraph2
  eval_func: mmgait_single_modal_evaluation
  sampler:
    batch_size: 8 
    frames_num_fixed: 60
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_ordered
    frames_skip_num: 0
  metric: cos
  transform:
    - type: Compose
      trf_cfg:
        - type: NormalizeEmpty
        - type: GaitGraph_MultiInput

loss_cfg:
  - loss_term_weight: 1
    temperature: 0.01
    type:  SupConLoss_Lp
    log_prefix: SupConLoss

model_cfg:
  model: GaitGraph2
  joint_format: coco
  input_num: 3
  reduction: 8
  block: Bottleneck # Basic, initial
  input_branch:
    - 5
    - 64
    - 32
  main_stream:
    - 32
    - 128
    - 256
  num_class: 200
  tta: true



optimizer_cfg:
  lr: 0.005 #0.005
  solver: AdamW
  weight_decay: 0.00001

scheduler_cfg:
  max_lr: 0.005
  total_steps: 3000
  scheduler: OneCycleLR


trainer_cfg:
  enable_float16: false #not use
  log_iter: 100
  with_test: true
  restore_ckpt_strict: false
  restore_hint: 0
  save_iter: 3000
  save_name: GaitGraph2
  sync_BN: true
  total_iter: 3000
  sampler:
    batch_shuffle: true
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_ordered #Repeat sample
    frames_skip_num: 0
    batch_size: 
      - 8
      - 16
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: PointNoise
          std: 0.05
        - type: GaitGraph_MultiInput